import type { Task } from "@/types";

export const mockTasks: Task[] = [
    {
        id: "t1",
        title: "Orçar barracas da festa junina",
        description: "Pedir preço pra 3 fornecedores e comparar",
        status: "todo",
        priority: "high",
        assignee: "Pedro",
        dueDate: "5 ago",
        createdAt: new Date("2026-07-20"),
    },
    {
        id: "t2",
        title: "Reservar a quadra",
        description: "Confirmar com a coordenação a data de 12 ago",
        status: "todo",
        priority: "medium",
        assignee: "Marina",
        dueDate: "7 ago",
        createdAt: new Date("2026-07-21"),
    },
    {
        id: "t3",
        title: "Lista de prêmios da gincana",
        description: "Levantar doações com os comércios do bairro",
        status: "todo",
        priority: "low",
        assignee: "Lucas",
        dueDate: "15 ago",
        createdAt: new Date("2026-07-22"),
    },
    {
        id: "t4",
        title: "Arte do cartaz",
        description: "Versão pra story e pra imprimir no mural",
        status: "progress",
        priority: "high",
        assignee: "Bia",
        dueDate: "3 ago",
        createdAt: new Date("2026-07-18"),
    },
    {
        id: "t5",
        title: "Autorização da direção",
        description: "Protocolar o pedido da gincana na secretaria",
        status: "progress",
        priority: "medium",
        assignee: "Marina",
        dueDate: "20 ago",
        createdAt: new Date("2026-07-19"),
    },
    {
        id: "t6",
        title: "Definir data da festa",
        description: "Fechado em reunião: 12 de agosto",
        status: "done",
        priority: "medium",
        assignee: "Marina",
        createdAt: new Date("2026-07-10"),
    },
    {
        id: "t7",
        title: "Criar o insta do grêmio",
        description: "Perfil no ar, senha com a comunicação",
        status: "done",
        priority: "low",
        assignee: "Bia",
        createdAt: new Date("2026-07-08"),
    },
];
